name: Build FrankenPHP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest FrankenPHP release
        id: frankenphp
        run: |
          LATEST=$(curl -s https://api.github.com/repos/dunglas/frankenphp/releases/latest | jq -r .tag_name)
          echo "version=${LATEST}" >> $GITHUB_OUTPUT

      - name: Checkout FrankenPHP
        uses: actions/checkout@v4
        with:
          repository: dunglas/frankenphp
          ref: ${{ steps.frankenphp.outputs.version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            golang-go

      - name: Build FrankenPHP
        run: |
          PHP_VERSION=8.3 ./build-static.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frankenphp-php8.3-${{ steps.frankenphp.outputs.version }}
          path: dist/frankenphp

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: php8.3-${{ steps.frankenphp.outputs.version }}
          name: FrankenPHP ${{ steps.frankenphp.outputs.version }} with PHP 8.3
          files: dist/frankenphp
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}